### ISSUE TITLE
I can't make a connection with hubiC

### ISSUE THREAD

**Issue by Issam2204** [oderwat/hubic2swiftgate#19]
Hello!

First of all thank you very much for everything!

I'm trying to make hubic2swiftgate work but I'm finding some trouble to access this address:

https://issam******.com/register/?client=hubic&password=mypassword

I have an 404 error. What I did is to make the necessary configuration in the file config.php, and the i renamed the folder "hubic2swiftgate-master" to "hsgate", and finally I put the folder in /var/www.

My website does work with SSL. Indeed now I can see the content  of /var/www/hsgate, but the I don't understand how to connect with hubiC.

Can someone please give me a hand?

Thanks!

**Comment by butterkekstorte** [comment]
If your Document root is `/var/www` and the gateway is in `/var/www/hsgate` the path you would need to connect to is `https://yourdomain/hsgate/register/....`

You get the 404 because your structure is not correct.
You either copy the contents of the folder `hsgate` directly into `/var/www` or use the path i told you and try your luck with that

This is not an issue of the gateway, but an installation issue.
